# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(468, 685)
        MainWindow.setStyleSheet("")
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 100, 261, 101))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("color: rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.botao_cadastrar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_cadastrar.setGeometry(QtCore.QRect(130, 300, 191, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.botao_cadastrar.setFont(font)
        self.botao_cadastrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_cadastrar.setMouseTracking(False)
        self.botao_cadastrar.setStyleSheet("background-color: rgb(190, 140, 100);\n"
"color: rgb(255, 255, 255);")
        self.botao_cadastrar.setCheckable(False)
        self.botao_cadastrar.setAutoDefault(False)
        self.botao_cadastrar.setDefault(False)
        self.botao_cadastrar.setFlat(False)
        self.botao_cadastrar.setObjectName("botao_cadastrar")
        self.botao_consultar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_consultar.setGeometry(QtCore.QRect(130, 450, 191, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botao_consultar.sizePolicy().hasHeightForWidth())
        self.botao_consultar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setUnderline(False)
        self.botao_consultar.setFont(font)
        self.botao_consultar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_consultar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botao_consultar.setStyleSheet("background-color: rgb(190, 140, 100);\n"
"color: rgb(255, 255, 255);")
        self.botao_consultar.setObjectName("botao_consultar")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(-180, -20, 801, 701))
        self.background.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.background.setStyleSheet("background-image:  url(\'C:/Users/suporte/Desktop/qt/nutri_mal/imagens/background_main.jpg\');\n"
"background-position: center;\n"
"background-repeat: no-repeat;\n"
"")
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("imagens/background_main.jpg"))
        self.background.setObjectName("background")
        self.background.raise_()
        self.label.raise_()
        self.botao_cadastrar.raise_()
        self.botao_consultar.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "NutriMal"))
        self.botao_cadastrar.setText(_translate("MainWindow", "Cadastrar \n"
"Novo Cliente"))
        self.botao_consultar.setText(_translate("MainWindow", "Acompanhar \n"
" Consultas Existentes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
