# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_consulta.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tela_consulta(object):
    def setupUi(self, tela_consulta):
        tela_consulta.setObjectName("tela_consulta")
        tela_consulta.resize(1197, 739)
        self.centralwidget = QtWidgets.QWidget(tela_consulta)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1197, 739))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("imagens/bg_consulta2.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.consulta_nome = QtWidgets.QLabel(self.centralwidget)
        self.consulta_nome.setGeometry(QtCore.QRect(220, 140, 721, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.consulta_nome.setFont(font)
        self.consulta_nome.setStyleSheet("color: white;")
        self.consulta_nome.setObjectName("consulta_nome")
        self.titulo_consulta = QtWidgets.QLabel(self.centralwidget)
        self.titulo_consulta.setGeometry(QtCore.QRect(490, 20, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(35)
        self.titulo_consulta.setFont(font)
        self.titulo_consulta.setStyleSheet("color: white;")
        self.titulo_consulta.setObjectName("titulo_consulta")
        self.consulta_lista = QtWidgets.QLabel(self.centralwidget)
        self.consulta_lista.setGeometry(QtCore.QRect(110, 280, 981, 411))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.consulta_lista.setFont(font)
        self.consulta_lista.setStyleSheet("background-color:rgba(0, 0, 0, 0.6);\n"
"color: white;")
        self.consulta_lista.setAlignment(QtCore.Qt.AlignCenter)
        self.consulta_lista.setObjectName("consulta_lista")
        self.consulta_obj = QtWidgets.QLabel(self.centralwidget)
        self.consulta_obj.setGeometry(QtCore.QRect(220, 200, 451, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.consulta_obj.setFont(font)
        self.consulta_obj.setStyleSheet("color: white;")
        self.consulta_obj.setObjectName("consulta_obj")
        self.botao_voltar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_voltar.setGeometry(QtCore.QRect(10, 10, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.botao_voltar.setFont(font)
        self.botao_voltar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.botao_voltar.setObjectName("botao_voltar")
        self.botao_consultar_user = QtWidgets.QPushButton(self.centralwidget)
        self.botao_consultar_user.setGeometry(QtCore.QRect(910, 130, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.botao_consultar_user.setFont(font)
        self.botao_consultar_user.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.botao_consultar_user.setObjectName("botao_consultar_user")
        self.input_user = QtWidgets.QLineEdit(self.centralwidget)
        self.input_user.setGeometry(QtCore.QRect(310, 140, 541, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.input_user.setFont(font)
        self.input_user.setText("")
        self.input_user.setFrame(False)
        self.input_user.setObjectName("input_user")
        self.botao_menu = QtWidgets.QPushButton(self.centralwidget)
        self.botao_menu.setGeometry(QtCore.QRect(10, 10, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.botao_menu.setFont(font)
        self.botao_menu.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.botao_menu.setObjectName("botao_menu")
        self.label_info = QtWidgets.QLabel(self.centralwidget)
        self.label_info.setGeometry(QtCore.QRect(350, 90, 471, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setUnderline(True)
        self.label_info.setFont(font)
        self.label_info.setStyleSheet("")
        self.label_info.setObjectName("label_info")
        tela_consulta.setCentralWidget(self.centralwidget)

        self.retranslateUi(tela_consulta)
        QtCore.QMetaObject.connectSlotsByName(tela_consulta)

    def retranslateUi(self, tela_consulta):
        _translate = QtCore.QCoreApplication.translate
        tela_consulta.setWindowTitle(_translate("tela_consulta", "MainWindow"))
        self.consulta_nome.setText(_translate("tela_consulta", "Nome: "))
        self.titulo_consulta.setText(_translate("tela_consulta", "Consulta"))
        self.consulta_lista.setText(_translate("tela_consulta", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.consulta_obj.setText(_translate("tela_consulta", "Objetivo: "))
        self.botao_voltar.setText(_translate("tela_consulta", "Voltar"))
        self.botao_consultar_user.setText(_translate("tela_consulta", "Consultar"))
        self.botao_menu.setText(_translate("tela_consulta", "Menu"))
        self.label_info.setText(_translate("tela_consulta", "Digite o NOME COMPLETO do paciente"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tela_consulta = QtWidgets.QMainWindow()
    ui = Ui_tela_consulta()
    ui.setupUi(tela_consulta)
    tela_consulta.show()
    sys.exit(app.exec_())
